apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sample
    app.kubernetes.io/part-of: july-app
  name: go-sample
  namespace: rhn-support-tshearon
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-sample
    weight: 100
status: {}
